### ISSUE TITLE
Requested Windows Runtime type 'Sqlite.Sqlite3' is not registered.

### ISSUE THREAD

**Issue by Mimetis** [peterhuene/sqlite-net-wp8#12]
HI,

I have an issue, when i tried to launch my Windows phone 8 sample
Every time I tried to open or make any request on SQLite, I have the same exception

A first chance exception of type 'System.TypeLoadException' occurred in MyProject.DLL

The Inner Exception is just a "class not registered"

Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
Requested Windows Runtime type 'Sqlite.Sqlite3' is not registered.

I have rebuild my project targeting x86, I have built your last C++ bits (version 3.7)
I couldn't make it work

Maybe, you have any suggestions ? :)

Thank you !

Sebastien

**Comment by peterhuene** [comment]
Since you're building x86, are you testing it on the emulator?  I haven't actually been able to test under the emulator, only on a physical device, since I run a Windows VM under VirtualBox (the emulator is actually a VM and HyperV can't virtualize without direct access to the hypervisor).

Was this working before or are you trying this out on 3.7.17 for the first time?

**Comment by Mimetis** [comment]
Thanks for the answer. I found my mystake. Just a bad reference.. 
I ve made test on the emulator (x86) and on my device (ARM) and it works.
Thanks for the good job !

**Comment by peterhuene** [comment]
I'm glad it's working for you.  Let me know if you run into any problems.

**Comment by mgwalm** [comment]
what bad reference? ive got the same problem!
