### ISSUE TITLE
Question: how to deal with native queries?

### ISSUE THREAD

**Issue by cwack-letsdev** [peterhuene/sqlite-net-wp8#16]
Hi Peter,

I would like to execute some native queries and currently I don't know, how to deal with at all. Do you have any tips for me? see below

Should I use your wrapper for that? If not how should I solve this. Already I did it within source code but I have some performance problems, of course.

Thx, KR Christian
- Select count(*) as countitems FROM....
- select DEPARTMENT,count(STAFF_ID) as CountStaff, avg(SALARY) as AVGSalary
  from STAFF
  group by DEPARTMENT
  having count(STAFF_ID) > 
- complex joins

**Comment by peterhuene** [comment]
This wrapper is really intended for consumption from sqlite-net.  If you're not planning on using sqlite-net, I'd probably create a small wrapper around the SQLite C API for what you actually need to do, assuming you need to access SQLite from managed code.

Are you using sqlite-net and noticing performance issues?  Keep in mind that like any embedded database, doing complex queries may never have stellar performance due to their limited memory-use designs.

**Comment by AndyCW** [comment]
We have such a wrapper at http://sqlwinrt.codeplex.com . This is an alternative to SQLite-net for devs who prefer to work with SQL statements.

Andy Wigley - Microsoft

Sent from Windows Mail

From: peterhuene
Sent: ‎Thursday‎, ‎25‎ ‎July‎ ‎2013 ‎18‎:‎35
To: peterhuene/sqlite-net-wp8

This wrapper is really intended for consumption from sqlite-net. If you're not planning on using sqlite-net, I'd probably create a small wrapper around the SQLite C API for what you actually need to do, assuming you need to access SQLite from managed code.

Are you using sqlite-net and noticing performance issues? Keep in mind that like any embedded database, doing complex queries may never have stellar performance due to their limited memory-use designs.
