### ISSUE TITLE
problem with sqlite 

### ISSUE THREAD

**Issue by muktigoutam** [peterhuene/sqlite-net-wp8#23]
Hello,

I am new with window phone application, i have developed an window phone app in c# in which i have used sqlite as well i had integrated sqlite successfully but when i have changed my machine and i ran my application on another machine then it was showing error in sqlite project, i tried to reload it but failed every time it failed then i removed it and tried to add it again then i am getting the following error please help me to resolve this problem .
![image](https://f.cloud.github.com/assets/5574079/1235503/09f9da3e-29a8-11e3-9bde-bf59dcc2e125.png)

**Comment by termvader** [comment]
I think you have installed a new version of SQLite for Windows Phone.
You can check out the version from Tools -> Extensions & Updates
The current version is 3.8.0.2
While your project is referring to version 3.7.1.7
Try downgrading the extension or get the latest master of this repo.

**Comment by peterhuene** [comment]
As termvader said, you will need to update sqlite-net-wp8 to the appropriate version (you can usually just pull the latest from master, as I push up a new reference whenever they update the extension).

**Comment by muktigoutam** [comment]
Thanks, i have updated it and resolved problem, now i am getting following error when rebuild the project 

"The type or namespace name 'Sqlite' could not be found (are you missing a using directive or an assembly reference?)"

**Comment by peterhuene** [comment]
Where are you observing the error?

**Comment by muktigoutam** [comment]
![image](https://f.cloud.github.com/assets/5574079/1259576/3243b850-2bee-11e3-9cda-dfe3aeb5b0f6.png)

**Comment by peterhuene** [comment]
And you're referencing the SQLite project as a project reference from your "APP TRAP" project?

**Comment by muktigoutam** [comment]
yes

**Comment by termvader** [comment]
Go to your Solution Explorer, you should see atleast two projects.
- Your App Trap
- Sqlite

Go to App Trap -> References, See if Sqlite is there in that list.
If not then right click on `References` and select `Add Reference`.
From the left hand pane select `Solution` and then select the checkbox for Sqlite in the center pane.

If you don't have Sqlite in your solution then select `Add Existing Project` and add it or add a precompiled dll to it. (Make sure its set for the same target platform as to where you are testing.)

Send us a screenshot of your Solution Explorer with References otherwise.

**Comment by muktigoutam** [comment]
Thank you so much......  I have followed above steps and my problem has been resolved.
